<?php
/**
 * The ImageAPI Optimize Kraken integration module.
 */

/**
 * Implements hook_image_effect_info_alter().
 */
function imageapi_optimize_kraken_image_effect_info_alter(&$effects) {
  // Remove the Kraken effect, as it doesn't really work.
  unset($effects['kraken_optimize']);
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function imageapi_optimize_kraken_form_system_image_toolkit_settings_alter(&$form, &$form_state) {
  // Hide the bits of the kraken module that we're replacing.
  if (isset($form['kraken']['api_key'])) {
    $form['kraken']['api_key']['#access'] = FALSE;
  }
  if (isset($form['kraken']['api_secret'])) {
    $form['kraken']['api_secret']['#access'] = FALSE;
  }
}
